### ISSUE TITLE
Update README.md to Standard format

### ISSUE THREAD

**Issue by Hrily** [Hrily/SH#1]
Include Instructions as to how to run the Android App!

Should include:
- Installation of apk on device
- Opening and Building of source in Android Studio, along with links to installation of Android Studio

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by heath3n** [comment]
Claiming and starting work.

**Comment by Hrily** [comment]
Okay,  work on it...  :)

**Comment by Hrily** [comment]
@HEATH3N 
Merged the request. Good job... :)
