### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by Hrily** [Hrily/SH#2]
Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by tomscholz** [comment]
Claimed

**Comment by Hrily** [comment]
Okay, work on it...  :)

**Comment by tomscholz** [comment]
@Hrily do you have a public email address to contact you? I want to implement the email in the CONTRIBUTING.md :)
_Update:_ I will use hrily@users.noreply.github.com

**Comment by Hrily** [comment]
Merged your request...  :+1: 
It's really a good work. Thank you... :)
